---

- name: galera_apt_get_update
  apt:
    update_cache: yes

- name: "restart mysql"
  service:
    name: mysql
    state: restarted

- name: "start mysql"
  service:
    name: mysql
    state: started

- name: stop mysql
  service:
    name: mysql
    state: stopped
